### ISSUE TITLE
Failing CI/CD build when application database is configured

### ISSUE THREAD

**Issue by alexkayabula** [azaria-dedmon/covid-19#30]
When the application database is configured, the build fails

**Comment by azaria-dedmon** [comment]
@alexkayabula Just out of curiosity, why are we only including the test database and not the main one in the Travis file?

**Comment by alexkayabula** [comment]
@azaria-dedmon having a `test database` in the travis file gives us the luxury to run tests against the `test database` without worrying about downtime or  breaking the application since its from the `main database` the application is running.
