### ISSUE TITLE
Application crashing when trying to view testing locations

### ISSUE THREAD

**Issue by alexkayabula** [azaria-dedmon/covid-19#45]
https://user-images.githubusercontent.com/31479458/109410077-aedb3400-79a8-11eb-9d9a-8bdebb2640b9.mov

**Comment by alexkayabula** [comment]
@azaria-dedmon Please close an issue with an accompanying reason for closure or a PR fix if required.

**Comment by azaria-dedmon** [comment]
@alexkayabula Would it be acceptable to link the PR that is currently open (which solves this bug) to this issue or should I be making a brand new PR?

**Comment by alexkayabula** [comment]
Create a different PR to fix this issue. The currently open PR is meant to implement a different feature.
