### ISSUE TITLE
Application is crashing

### ISSUE THREAD

**Issue by alexkayabula** [azaria-dedmon/covid-19#50]
@azaria-dedmon this issue is reoccurring. Please look into it. Consider this a priority.

https://user-images.githubusercontent.com/31479458/109631875-77f75080-7b57-11eb-82d2-a16f8abaeb5c.mov

**Comment by azaria-dedmon** [comment]
@alexkayabula I've just checked the application and everything is running fine; the app never crashes for me.  I'll look into why this could be happening.

**Comment by azaria-dedmon** [comment]
@alexkayabula Just wondering, considering that all of the application's tests are passing and the application is not crashing for me, could it possibly be an issue with your machine?
