### ISSUE TITLE
Update Readme.md documentation

### ISSUE THREAD

**Issue by alexkayabula** [azaria-dedmon/covid-19#58]
Update the documentation with setup instructions and features and endpoints. Use the links below for reference.
[https://github.com/blakes24/dive-atlas#setup-instructions](https://github.com/blakes24/dive-atlas#setup-instructions)
[https://github.com/Huulamnguyen/can-cook#features--endpoint](https://github.com/Huulamnguyen/can-cook#features--endpoint)

**Comment by azaria-dedmon** [comment]
@alexkayabula Is it necessary to include the setup instructions for the project in the README.md file?

**Comment by alexkayabula** [comment]
Yes it is. If a user wanted to test out your application, they should be able to follow the instructions in the Remade file to set up.

**Comment by azaria-dedmon** [comment]
> Yes it is. If a user wanted to test out your application, they should be able to follow the instructions in the Remade file to set up.

okay
